import * as svt from "simple-validation-tools";

export enum Spell {
  Clumsy = "clumsy",
  CreateFood = "create food",
  Feeblemind = "feeblemind",
  Heal = "heal",
  MagicArrow = "magic arrow",
  NightSight = "night sight",
  ReactiveArmor = "reactive armor",
  Weaken = "weaken",
  Agility = "agility",
  Cunning = "cunning",
  Cure = "cure",
  Harm = "harm",
  MagicTrap = "magic trap",
  MagicUntrap = "magic untrap",
  Protection = "protection",
  Strength = "strength",
  Bless = "bless",
  Fireball = "fireball",
  MagicLock = "magic lock",
  Poison = "poison",
  Telekinesis = "telekinesis",
  Teleport = "teleport",
  Unlock = "unlock",
  WallOfStone = "wall of stone",
  ArchCure = "arch cure",
  ArchProtection = "arch protection",
  Curse = "curse",
  FireField = "fire field",
  GreaterHeal = "greater heal",
  Lightning = "lightning",
  ManaDrain = "mana drain",
  Recall = "recall",
  BladeSpirits = "blade spirits",
  DispelField = "dispel field",
  Incognito = "incognito",
  MagicReflection = "magic reflection",
  MindBlast = "mind blast",
  Paralyze = "paralyze",
  PoisonField = "poison field",
  SummonCreature = "summon creature",
  Dispel = "dispel",
  EnergyBolt = "energy bolt",
  Explosion = "explosion",
  Invisibility = "invisibility",
  Mark = "mark",
  MassCurse = "mass curse",
  ParalyzeField = "paralyze field",
  Reveal = "reveal",
  ChainLightning = "chain lightning",
  EnergyField = "energy field",
  Flamestrike = "flamestrike",
  GateTravel = "gate travel",
  ManaVampire = "mana vampire",
  MassDispel = "mass dispel",
  MeteorSwarm = "meteor swarm",
  Polymorph = "polymorph",
  Earthquake = "earthquake",
  EnergyVortex = "energy vortex",
  Resurrection = "resurrection",
  SummonAirElemental = "summon air elemental",
  SummonDaemon = "summon daemon",
  SummonEarthElemental = "summon earth elemental",
  SummonFireElemental = "summon fire elemental",
  SummonWaterElemental = "summon water elemental",
}

export function isSpell(value: unknown): value is Spell {
  return [
    Spell.Clumsy,
    Spell.CreateFood,
    Spell.Feeblemind,
    Spell.Heal,
    Spell.MagicArrow,
    Spell.NightSight,
    Spell.ReactiveArmor,
    Spell.Weaken,
    Spell.Agility,
    Spell.Cunning,
    Spell.Cure,
    Spell.Harm,
    Spell.MagicTrap,
    Spell.MagicUntrap,
    Spell.Protection,
    Spell.Strength,
    Spell.Bless,
    Spell.Fireball,
    Spell.MagicLock,
    Spell.Poison,
    Spell.Telekinesis,
    Spell.Teleport,
    Spell.Unlock,
    Spell.WallOfStone,
    Spell.ArchCure,
    Spell.ArchProtection,
    Spell.Curse,
    Spell.FireField,
    Spell.GreaterHeal,
    Spell.Lightning,
    Spell.ManaDrain,
    Spell.Recall,
    Spell.BladeSpirits,
    Spell.DispelField,
    Spell.Incognito,
    Spell.MagicReflection,
    Spell.MindBlast,
    Spell.Paralyze,
    Spell.PoisonField,
    Spell.SummonCreature,
    Spell.Dispel,
    Spell.EnergyBolt,
    Spell.Explosion,
    Spell.Invisibility,
    Spell.Mark,
    Spell.MassCurse,
    Spell.ParalyzeField,
    Spell.Reveal,
    Spell.ChainLightning,
    Spell.EnergyField,
    Spell.Flamestrike,
    Spell.GateTravel,
    Spell.ManaVampire,
    Spell.MassDispel,
    Spell.MeteorSwarm,
    Spell.Polymorph,
    Spell.Earthquake,
    Spell.EnergyVortex,
    Spell.Resurrection,
    Spell.SummonAirElemental,
    Spell.SummonDaemon,
    Spell.SummonEarthElemental,
    Spell.SummonFireElemental,
    Spell.SummonWaterElemental,
  ].some((v) => v === value);
}

export function validateSpell(value: unknown): svt.ValidationResult<Spell> {
  return svt.validateOneOfLiterals<Spell>(value, [
    Spell.Clumsy,
    Spell.CreateFood,
    Spell.Feeblemind,
    Spell.Heal,
    Spell.MagicArrow,
    Spell.NightSight,
    Spell.ReactiveArmor,
    Spell.Weaken,
    Spell.Agility,
    Spell.Cunning,
    Spell.Cure,
    Spell.Harm,
    Spell.MagicTrap,
    Spell.MagicUntrap,
    Spell.Protection,
    Spell.Strength,
    Spell.Bless,
    Spell.Fireball,
    Spell.MagicLock,
    Spell.Poison,
    Spell.Telekinesis,
    Spell.Teleport,
    Spell.Unlock,
    Spell.WallOfStone,
    Spell.ArchCure,
    Spell.ArchProtection,
    Spell.Curse,
    Spell.FireField,
    Spell.GreaterHeal,
    Spell.Lightning,
    Spell.ManaDrain,
    Spell.Recall,
    Spell.BladeSpirits,
    Spell.DispelField,
    Spell.Incognito,
    Spell.MagicReflection,
    Spell.MindBlast,
    Spell.Paralyze,
    Spell.PoisonField,
    Spell.SummonCreature,
    Spell.Dispel,
    Spell.EnergyBolt,
    Spell.Explosion,
    Spell.Invisibility,
    Spell.Mark,
    Spell.MassCurse,
    Spell.ParalyzeField,
    Spell.Reveal,
    Spell.ChainLightning,
    Spell.EnergyField,
    Spell.Flamestrike,
    Spell.GateTravel,
    Spell.ManaVampire,
    Spell.MassDispel,
    Spell.MeteorSwarm,
    Spell.Polymorph,
    Spell.Earthquake,
    Spell.EnergyVortex,
    Spell.Resurrection,
    Spell.SummonAirElemental,
    Spell.SummonDaemon,
    Spell.SummonEarthElemental,
    Spell.SummonFireElemental,
    Spell.SummonWaterElemental,
  ]);
}
